"""add source_quote to annotations

Revision ID: 243f4bf0214a
Revises: 2568dd7579ee
Create Date: 2026-06-17 13:15:24.618053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243f4bf0214a'
down_revision: Union[str, Sequence[str], None] = '2568dd7579ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('source_quote', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'source_quote')
    # ### end Alembic commands ###
