"""drop scripts yaml_content column

Revision ID: 2568dd7579ee
Revises: 736a4dae8199
Create Date: 2026-06-17 12:50:53.594976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2568dd7579ee'
down_revision: Union[str, Sequence[str], None] = '736a4dae8199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'yaml_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('yaml_content', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
