"""add blocks table and extend scenes for db source of truth

Revision ID: 736a4dae8199
Revises: db8ae2621251
Create Date: 2026-06-16 22:32:55.577014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736a4dae8199'
down_revision: Union[str, Sequence[str], None] = 'db8ae2621251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('char_id', sa.Uuid(), nullable=True),
    sa.Column('char_name', sa.String(length=255), nullable=True),
    sa.Column('parenthetical', sa.Text(), nullable=True),
    sa.Column('line', sa.Text(), nullable=True),
    sa.Column('annotation_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scenes', sa.Column('characters_present', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('scenes', sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('scenes', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_column('scenes', 'yaml_snippet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('yaml_snippet', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('scenes', 'order')
    op.drop_column('scenes', 'props')
    op.drop_column('scenes', 'characters_present')
    op.drop_table('blocks')
    # ### end Alembic commands ###
