"""add annotation status field

Revision ID: bb62ae6e7feb
Revises: ebf27d19ad5a
Create Date: 2026-06-05 23:30:07.509233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb62ae6e7feb'
down_revision: Union[str, Sequence[str], None] = 'ebf27d19ad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'status')
    # ### end Alembic commands ###
